tunnel: 173e5515-cdf3-4140-b8c4-ad87bf3737df
credentials-file: /Users/pranavgupta/.cloudflared/173e5515-cdf3-4140-b8c4-ad87bf3737df.json 

ingress:
  - hostname: dev.pharmagpt.co
    path: ^/(auth|invoices|products|reporting|inventory|system|config|feedback|activity-log|history|export-excel|invitations|report|metrics)(/.*)?$
    service: http://127.0.0.1:5005
    originRequest:
      connectTimeout: 60s
      noTLSVerify: true
      proxyKeepAlive: 30s
  - hostname: grafana.pharmagpt.co
    service: http://127.0.0.1:3001
  - hostname: monitoring.pharmagpt.co
    service: http://127.0.0.1:3001
  - hostname: dev.pharmagpt.co
    service: http://127.0.0.1:3000
    originRequest:
      connectTimeout: 60s
      noTLSVerify: true
      proxyKeepAlive: 30s
  - hostname: pharmagpt.co
    service: http://127.0.0.1:3000
    originRequest:
      connectTimeout: 60s
  - hostname: api.pharmagpt.co
    service: http://127.0.0.1:5005
    originRequest:
      connectTimeout: 60s
  - service: http_status:404
