{
 "title": "Invoice Extractor Full Stack Observability",
 "tags": [
  "fastapi",
  "loki",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "API Requests Rate (by handler)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "API Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latency (s)"
    }
   ]
  },
  {
   "title": "Application Backend Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"backend-app\"}"
    }
   ]
  }
 ]
}